# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [1]:
import numpy as np

In [6]:
np.random.randint(0, 20, size = (4, 7))

array([[ 4, 10, 12, 18,  3,  0, 12],
       [ 0,  8,  6,  4,  2,  1, 11],
       [ 8, 17,  1, 10, 17,  6,  8],
       [ 7,  1,  9, 11,  6, 16, 11]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [7]:
np.random.randint(0, 10, size = (8, 10))

array([[3, 7, 9, 1, 9, 6, 9, 3, 2, 9],
       [7, 8, 9, 7, 8, 3, 1, 5, 3, 9],
       [1, 4, 2, 3, 9, 4, 1, 5, 4, 1],
       [1, 4, 7, 9, 4, 7, 6, 8, 7, 8],
       [0, 9, 4, 7, 8, 4, 5, 2, 4, 6],
       [6, 1, 2, 9, 6, 8, 1, 9, 0, 2],
       [5, 2, 4, 5, 9, 2, 1, 7, 5, 1],
       [9, 2, 8, 5, 1, 4, 7, 9, 6, 2]])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [10]:
import matplotlib.pyplot as pl
from mpl_toolkits.mplot3d import Axes3D

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [127]:
import numpy as np
 
data = np.loadtxt("minutes_n_ingredients.csv", delimiter=',', skiprows=1, dtype=np.int32)

for x in range(5):
    print(data[x])

[127244     60     16]
[23891    25     7]
[94746    10     6]
[67660     5     6]
[157911     60     14]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [21]:
c = np.mean(data, axis = 0)
b = np.max(data, axis = 0)
a = np.min(data, axis = 0)
d = np.median(data,axis = 0)

array([2.071935e+05, 4.000000e+01, 9.000000e+00])

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [173]:
d = np.quantile(data[:,1], 0.75)
d

65.0

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [163]:
d = np.where(data[:,1]==0)
len(d[0])

479

In [165]:
np.place(data[:,1], data[:,1] == 0, 1)
d = np.where(data[:,1]==0)
d

(array([], dtype=int64),)

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [32]:
d = np.unique(data, axis = 0)
len(d)

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [39]:
d = np.unique(data[: , 2], axis = 0, return_counts=True)
d

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 37, 39]),
 array([   13,   926,  2895,  5515,  7913,  9376, 10628, 10951, 10585,
         9591,  8297,  6605,  4997,  3663,  2595,  1767,  1246,   790,
          573,   376,   217,   161,   105,    69,    50,    28,    16,
           16,    12,    12,     3,     1,     2,     1,     3,     1,
            1], dtype=int64))

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [79]:
c = data[data[:,2] <=5]
for x in range(5):
    print(c[x])

[446597     15      5]
[204134      5      3]
[25623     6     4]
[484223     18      4]
[63150   250     4]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [85]:
d = data[:,2]/data[:,1]
print(d.max())

24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [104]:
data[:,1][::-1].sort()
d = data[:100]
np.mean(d[:,2], axis = 0)

28.22

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [124]:
randomRow = np.random.randint(100000, size=10)
for x in range(10):
    print(data[randomRow[x], :])

[78455    15     6]
[64032    55    10]
[275842     35      8]
[264462     45      9]
[5392   25    7]
[328493     25      7]
[55414   185    15]
[30457    20     6]
[202946     25      7]
[429195     45     10]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [137]:
a = np.mean(data[:,2], axis = 0)
d = np.where(data[:,2]<a)
print(len(d[0])/100000*100)

58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [157]:
col = np.where(np.logical_and(data[:,1]<=20,data[:,2]<=5), 1, 0)
d = data
c = np.column_stack((d,col))
for x in range(30):
   print(c[x])

[127244     60     16      0]
[23891    25     7     0]
[94746    10     6     0]
[67660     5     6     0]
[157911     60     14      0]
[152828     40      7      0]
[33941    18     9     0]
[446597     15      5      1]
[366174      7      9      0]
[74205    20     7     0]
[504666     65     20      0]
[81006    12     7     0]
[280968     85     11      0]
[204134      5      3      1]
[18593    35     7     0]
[25623     6     4     1]
[65559    24    14     0]
[99836   180     7     0]
[87775    80    13     0]
[425704     40     12      0]
[101799     10      8      0]
[106325     70     11      0]
[99283   315     6     0]
[179504    150     11      0]
[276123     60      7      0]
[498382     85     18      0]
[197140     40      6      0]
[484223     18      4      1]
[385472     90      9      0]
[63150   250     4     0]


13. Выведите процент "простых" рецептов в датасете

In [162]:
d = np.where(c[:,3] == 1)
print(len(d[0])/100000*100)

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.